### ISSUE TITLE
启动直接报错怎么回事呀？

### ISSUE THREAD

**Issue by galaxist** [tangaiyun/redislimiter-spring-boot#3]
D:\works\java\jdk1.8.0\bin\java.exe -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:51755,suspend=y,server=n -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -javaagent:D:\works\JetBrains\ideaIU-2019.1.3.win\lib\rt\debugger-agent.jar -Dfile.encoding=UTF-8 -classpath D:\works\java\jdk1.8.0\jre\lib\charsets.jar;D:\works\java\jdk1.8.0\jre\lib\deploy.jar;D:\works\java\jdk1.8.0\jre\lib\ext\access-bridge-64.jar;D:\works\java\jdk1.8.0\jre\lib\ext\cldrdata.jar;D:\works\java\jdk1.8.0\jre\lib\ext\dnsns.jar;D:\works\java\jdk1.8.0\jre\lib\ext\jaccess.jar;D:\works\java\jdk1.8.0\jre\lib\ext\jfxrt.jar;D:\works\java\jdk1.8.0\jre\lib\ext\localedata.jar;D:\works\java\jdk1.8.0\jre\lib\ext\nashorn.jar;D:\works\java\jdk1.8.0\jre\lib\ext\sunec.jar;D:\works\java\jdk1.8.0\jre\lib\ext\sunjce_provider.jar;D:\works\java\jdk1.8.0\jre\lib\ext\sunmscapi.jar;D:\works\java\jdk1.8.0\jre\lib\ext\sunpkcs11.jar;D:\works\java\jdk1.8.0\jre\lib\ext\zipfs.jar;D:\works\java\jdk1.8.0\jre\lib\javaws.jar;D:\works\java\jdk1.8.0\jre\lib\jce.jar;D:\works\java\jdk1.8.0\jre\lib\jfr.jar;D:\works\java\jdk1.8.0\jre\lib\jfxswt.jar;D:\works\java\jdk1.8.0\jre\lib\jsse.jar;D:\works\java\jdk1.8.0\jre\lib\management-agent.jar;D:\works\java\jdk1.8.0\jre\lib\plugin.jar;D:\works\java\jdk1.8.0\jre\lib\resources.jar;D:\works\java\jdk1.8.0\jre\lib\rt.jar;D:\works\VersionControl\github\tangaiyun\redislimiter-spring-boot\demo1\target\classes;D:\works\MavenRepository\org\springframework\boot\spring-boot-starter\2.1.0.RELEASE\spring-boot-starter-2.1.0.RELEASE.jar;D:\works\MavenRepository\org\springframework\boot\spring-boot\2.1.0.RELEASE\spring-boot-2.1.0.RELEASE.jar;D:\works\MavenRepository\org\springframework\spring-context\5.1.2.RELEASE\spring-context-5.1.2.RELEASE.jar;D:\works\MavenRepository\org\springframework\boot\spring-boot-autoconfigure\2.1.0.RELEASE\spring-boot-autoconfigure-2.1.0.RELEASE.jar;D:\works\MavenRepository\org\springframework\boot\spring-boot-starter-logging\2.1.0.RELEASE\spring-boot-starter-logging-2.1.0.RELEASE.jar;D:\works\MavenRepository\ch\qos\logback\logback-classic\1.2.3\logback-classic-1.2.3.jar;D:\works\MavenRepository\ch\qos\logback\logback-core\1.2.3\logback-core-1.2.3.jar;D:\works\MavenRepository\org\apache\logging\log4j\log4j-to-slf4j\2.11.1\log4j-to-slf4j-2.11.1.jar;D:\works\MavenRepository\org\apache\logging\log4j\log4j-api\2.11.1\log4j-api-2.11.1.jar;D:\works\MavenRepository\org\slf4j\jul-to-slf4j\1.7.25\jul-to-slf4j-1.7.25.jar;D:\works\MavenRepository\javax\annotation\javax.annotation-api\1.3.2\javax.annotation-api-1.3.2.jar;D:\works\MavenRepository\org\springframework\spring-core\5.1.2.RELEASE\spring-core-5.1.2.RELEASE.jar;D:\works\MavenRepository\org\springframework\spring-jcl\5.1.2.RELEASE\spring-jcl-5.1.2.RELEASE.jar;D:\works\MavenRepository\org\yaml\snakeyaml\1.23\snakeyaml-1.23.jar;D:\works\MavenRepository\org\springframework\boot\spring-boot-starter-web\2.1.0.RELEASE\spring-boot-starter-web-2.1.0.RELEASE.jar;D:\works\MavenRepository\org\springframework\boot\spring-boot-starter-json\2.1.0.RELEASE\spring-boot-starter-json-2.1.0.RELEASE.jar;D:\works\MavenRepository\com\fasterxml\jackson\core\jackson-databind\2.9.7\jackson-databind-2.9.7.jar;D:\works\MavenRepository\com\fasterxml\jackson\core\jackson-annotations\2.9.0\jackson-annotations-2.9.0.jar;D:\works\MavenRepository\com\fasterxml\jackson\core\jackson-core\2.9.7\jackson-core-2.9.7.jar;D:\works\MavenRepository\com\fasterxml\jackson\datatype\jackson-datatype-jdk8\2.9.7\jackson-datatype-jdk8-2.9.7.jar;D:\works\MavenRepository\com\fasterxml\jackson\datatype\jackson-datatype-jsr310\2.9.7\jackson-datatype-jsr310-2.9.7.jar;D:\works\MavenRepository\com\fasterxml\jackson\module\jackson-module-parameter-names\2.9.7\jackson-module-parameter-names-2.9.7.jar;D:\works\MavenRepository\org\springframework\boot\spring-boot-starter-tomcat\2.1.0.RELEASE\spring-boot-starter-tomcat-2.1.0.RELEASE.jar;D:\works\MavenRepository\org\apache\tomcat\embed\tomcat-embed-core\9.0.12\tomcat-embed-core-9.0.12.jar;D:\works\MavenRepository\org\apache\tomcat\embed\tomcat-embed-el\9.0.12\tomcat-embed-el-9.0.12.jar;D:\works\MavenRepository\org\apache\tomcat\embed\tomcat-embed-websocket\9.0.12\tomcat-embed-websocket-9.0.12.jar;D:\works\MavenRepository\org\hibernate\validator\hibernate-validator\6.0.13.Final\hibernate-validator-6.0.13.Final.jar;D:\works\MavenRepository\javax\validation\validation-api\2.0.1.Final\validation-api-2.0.1.Final.jar;D:\works\MavenRepository\org\jboss\logging\jboss-logging\3.3.2.Final\jboss-logging-3.3.2.Final.jar;D:\works\MavenRepository\com\fasterxml\classmate\1.4.0\classmate-1.4.0.jar;D:\works\MavenRepository\org\springframework\spring-web\5.1.2.RELEASE\spring-web-5.1.2.RELEASE.jar;D:\works\MavenRepository\org\springframework\spring-beans\5.1.2.RELEASE\spring-beans-5.1.2.RELEASE.jar;D:\works\MavenRepository\org\springframework\spring-webmvc\5.1.2.RELEASE\spring-webmvc-5.1.2.RELEASE.jar;D:\works\MavenRepository\org\springframework\spring-aop\5.1.2.RELEASE\spring-aop-5.1.2.RELEASE.jar;D:\works\MavenRepository\org\springframework\spring-expression\5.1.2.RELEASE\spring-expression-5.1.2.RELEASE.jar;D:\works\MavenRepository\org\projectlombok\lombok\1.18.2\lombok-1.18.2.jar;D:\works\MavenRepository\org\slf4j\slf4j-api\1.7.25\slf4j-api-1.7.25.jar;D:\works\MavenRepository\com\tay\redislimiter-spring-boot-starter\0.0.1-SNAPSHOT\redislimiter-spring-boot-starter-0.0.1-20190621.032240-1.jar;D:\works\MavenRepository\redis\clients\jedis\2.9.0\jedis-2.9.0.jar;D:\works\MavenRepository\org\apache\commons\commons-pool2\2.6.0\commons-pool2-2.6.0.jar;D:\works\MavenRepository\com\github\ben-manes\caffeine\caffeine\2.6.2\caffeine-2.6.2.jar;D:\works\JetBrains\ideaIU-2019.1.3.win\lib\idea_rt.jar com.tay.demo1.Demo1Application
Connected to the target VM, address: '127.0.0.1:51755', transport: 'socket'

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.0.RELEASE)

2019-06-21 12:59:13.121  INFO 244 --- [           main] com.tay.demo1.Demo1Application           : Starting Demo1Application on DESKTOP-CGMBOD8 with PID 244 (D:\works\VersionControl\github\tangaiyun\redislimiter-spring-boot\demo1\target\classes started by Administrator in D:\works\VersionControl\github\tangaiyun\redislimiter-spring-boot\demo1)
2019-06-21 12:59:13.125  INFO 244 --- [           main] com.tay.demo1.Demo1Application           : No active profile set, falling back to default profiles: default
2019-06-21 12:59:13.762  INFO 244 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'spring.redis-limiter-com.tay.redislimiter.RedisLimiterProperties' of type [com.tay.redislimiter.RedisLimiterProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-06-21 12:59:13.764  INFO 244 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'com.tay.redislimiter.RedisLimiterConfiguration' of type [com.tay.redislimiter.RedisLimiterConfiguration$$EnhancerBySpringCGLIB$$4af64941] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
Exception in thread "Thread-4" redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required.
	at redis.clients.jedis.Protocol.processError(Protocol.java:127)
	at redis.clients.jedis.Protocol.process(Protocol.java:161)
	at redis.clients.jedis.Protocol.read(Protocol.java:215)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
	at redis.clients.jedis.Connection.getRawObjectMultiBulkReply(Connection.java:285)
	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:121)
	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:115)
	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2680)
	at com.tay.redislimiter.dynamic.RedisLimiterConfigProcessor$SubThread.run(RedisLimiterConfigProcessor.java:80)
2019-06-21 12:59:14.001  INFO 244 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8888 (http)
2019-06-21 12:59:14.019  INFO 244 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2019-06-21 12:59:14.019  INFO 244 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/9.0.12
2019-06-21 12:59:14.027  INFO 244 --- [           main] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [D:\works\java\jdk1.8.0\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\VanDyke Software\Clients\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\TortoiseGit\bin;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;D:\works\java\jdk1.8.0\bin;D:\works\nodejs\node-v10.15.3-win-x64;;.]
2019-06-21 12:59:14.118  INFO 244 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2019-06-21 12:59:14.119  INFO 244 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 952 ms
2019-06-21 12:59:14.143  INFO 244 --- [           main] o.s.b.w.servlet.ServletRegistrationBean  : Servlet dispatcherServlet mapped to [/]
2019-06-21 12:59:14.147  INFO 244 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2019-06-21 12:59:14.147  INFO 244 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-06-21 12:59:14.147  INFO 244 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'formContentFilter' to: [/*]
2019-06-21 12:59:14.147  INFO 244 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2019-06-21 12:59:14.370  INFO 244 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2019-06-21 12:59:14.537  INFO 244 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8888 (http) with context path ''
2019-06-21 12:59:14.541  INFO 244 --- [           main] com.tay.demo1.Demo1Application           : Started Demo1Application in 1.834 seconds (JVM running for 2.566)
2019-06-21 13:00:21.351  INFO 244 --- [nio-8888-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-06-21 13:00:21.351  INFO 244 --- [nio-8888-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2019-06-21 13:00:21.357  INFO 244 --- [nio-8888-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 6 ms
my check ####Access rate check task executed failed.

**Comment by tangaiyun** [comment]
看起来是你的redis server配置了密码

**Comment by tangaiyun** [comment]
如果你的redis server是有密码(假如密码为xxxx)，需要在配置文件里指定



spring.redis-limiter.redis-password: xxxx
